# -*- coding: utf-8 -*-
"""Top_10_words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iSnZjF1Dao3Cy-ueUE5yl5Eip4oSkmI
"""

!pip install nltk

import nltk
nltk.download('gutenberg')
nltk.corpus.gutenberg.fileids()

gutenberg=nltk.corpus.gutenberg.words('shakespeare-macbeth.txt')
gutenberg

import string
table = str.maketrans('', '', string.punctuation)
stripped = [w.translate(table) for w in gutenberg]

import matplotlib as plot
freq=nltk.FreqDist(stripped)
print(freq.most_common(11))

